#!/usr/bin/env python3

import infinit.beyond.bottle

import unittest
import urllib.parse

from utils import *

from copy import deepcopy

with Beyond() as beyond:

  class Test(unittest.TestCase):

    def test_normal(self):
      user = User()
      user.put(beyond)
      network = Network('server1,server2', owner = user)
      network.put(beyond)
      volume = Volume('business', network = network)
      volume.put(beyond)
      beyond.get('volumes/%s' % volume['name'])
      beyond.delete('volumes/%s' % volume['name'],
                    auth = user.private_key)
      throws(lambda: beyond.get('volumes/%s' % volume['name'],
                                json = False),
             404)

  if __name__ == '__main__':
    unittest.main()
