#!/usr/bin/env python3

import infinit.beyond.bottle

import unittest
import urllib.parse
from operator import itemgetter

from utils import *

class Test(unittest.TestCase):

  def test_normal(self):
    with Beyond() as beyond:
      user = User()
      user.put(beyond)
      network = Network(name = 'server1-server2', owner = user)
      network.put(beyond)
      volume = Volume(name = 'business', network = network)
      throws(lambda: beyond.get('volumes/%s' % volume['name']),
             404,
             json = False)
      volume.put(beyond)
      res = beyond.get('volumes/%s' % volume['name']).json()
      assertEq(res['name'], volume['name'])
      assertEq(res['network'], network['name'])
      res = beyond.get('networks/%s/volumes' % network['name']).json()
      assertEq(len(res['volumes']), 1)
      assertEq(res['volumes'][0]['name'], volume['name'])
      res = beyond.get('users/%s/volumes' % user['name'],
                       auth = user).json()
      assertEq(len(res['volumes']), 1)
      assertEq(res['volumes'][0]['name'], volume['name'])

  def test_all(self):
    with Beyond() as beyond:
      user = User()
      user.put(beyond)
      network = Network(name = 'server1-server2', owner = user)
      network.put(beyond)
      volume = Volume(name = 'business', network = network)
      volume.put(beyond)
      volume2 = Volume(name = 'fun', network = network)
      volume2.put(beyond)
      res = beyond.get('users/%s/volumes' % user['name'],
                       auth = user).json()
      volumes = sorted(res['volumes'], key = itemgetter('name'))
      assertEq(len(volumes), 2)
      assertEq(volumes[0]['network'], volumes[1]['network'], network['name'])
      assertEq(volumes[0]['name'], volume['name'])
      assertEq(volumes[1]['name'], volume2['name'])

  def test_on_network_you_dont_own(self):
    with Beyond() as beyond:
      user = User()
      user2 = User()
      user.put(beyond)
      user2.put(beyond)
      network = Network(name = 'server1-server2', owner = user)
      network.put(beyond)
      volume = Volume(name = 'business', network = network, owner = user2)
      volume.put(beyond)
      volume2 = Volume(name = 'business2', network = network, owner = user2)
      volume2.put(beyond)
      res = beyond.get('users/%s/volumes' % user2['name'],
                       auth = user2).json()
      volumes = sorted(res['volumes'], key = itemgetter('name'))
      print(volumes)
      assertEq(len(volumes), 2)
      assertEq(volumes[0]['network'], volumes[1]['network'], network['name'])
      assertEq(volumes[0]['name'], volume['name'])
      assertEq(volumes[1]['name'], volume2['name'])

if __name__ == '__main__':
  unittest.main()
