#!/usr/bin/env python3

import infinit.beyond.bottle

import unittest
import urllib.parse

from utils import *

from copy import deepcopy

with Beyond() as beyond:

  class Test(unittest.TestCase):

    def test_normal(self):
      user = User()
      user.put(beyond)
      network = Network(name = 'server1,server2', owner = user)
      network.put(beyond)
      volume = Volume(name = 'business', network = network)
      throws(lambda: beyond.get('volumes/%s' % volume['name']),
             404,
             json = False)
      volume.put(beyond)
      res = beyond.get('volumes/%s' % volume['name']).json()
      assertEq(res['name'], volume['name'])
      assertEq(res['network'], network['name'])
      res = beyond.get('networks/%s/volumes' % network['name']).json()
      assertEq(len(res['volumes']), 1)
      assertEq(res['volumes'][0]['name'], volume['name'])

  if __name__ == '__main__':
    unittest.main()
