#!/usr/bin/env python3

import infinit.beyond.bottle

import unittest
import urllib.parse

from utils import *

from copy import deepcopy

with Beyond() as beyond:

  class Test(unittest.TestCase):

    def test_normal(self):
      user = User()
      user.put(beyond)
      network = Network('server1,server2', owner = user)
      network.put(beyond)
      volume = Volume('business', network = network)
      throws(lambda: beyond.get('volumes/%s' % volume['name']),
             404,
             json = False)
      volume.put(beyond)
      res = beyond.get('volumes/%s' % volume['name']).json()
      assert res['name'] == volume['name']
      assert res['network'] == network['name']

  def test_already_pushed(self):
    # Test same already pushed
    user = User()
    user.put(beyond)
    network = Network('infinit', owner = user)
    network.put(beyond)
    volume = Volume('stuff', network = network)
    res = volume.put(beyond)
    asserEq(res.status_code, 201)
    res = volume.put(beyond)
    asserEq(res.status_code, 200)
    # Test conflict
    volume['network'] = 'foo/bar'
    throws(lambda: volume.put(beyond), 409)

  if __name__ == '__main__':
    unittest.main()
