#!/usr/bin/env python3

import os
import subprocess
import sys

arch, osyst, compiler = os.environ['BUILDFARM_NAME'].split('-')
os.chdir(os.environ['DIR_BUILD'])
subprocess.check_call(['python3', 'drake',
                       '//install', '//beyond/debian',
                       '--prefix=../%s' % os.environ['DIR_INSTALL']])
