#!/usr/bin/env python3

import os
import subprocess
import sys

arch, osyst, compiler = os.environ['BUILDFARM_NAME'].split('-')
os.chdir(os.environ['DIR_BUILD'])
targets = ['//install']

if osyst.startswith('linux_ubuntu'):
  targets.append('//beyond/debian')
  targets.append('//website/debian')

if osyst.startswith('linux_debian'):
  targets.append('//debian')

subprocess.check_call(
  ['python3', 'drake', '--prefix=../%s' % os.environ['DIR_INSTALL']]
  + targets)
