#!/usr/bin/env python3

import os
import subprocess

arch, osyst, comp = os.environ['BUILDFARM_NAME'].split('-')

os.chdir('%s' % os.environ['DIR_BUILD'])
jobs = 2 if osyst == 'osx' else os.environ['JOBS']
if subprocess.call(['python3', 'drake', '-j', str(jobs), '//check']) != 0:
  exit(1)
