#!/usr/bin/env python3

import os
import subprocess

arch, osyst, comp = os.environ['BUILDFARM_NAME'].split('-')

os.chdir('%s' % os.environ['DIR_BUILD'])
jobs = os.environ['JOBS']
if osyst == 'osx':
  jobs = str(int(int(jobs) / 2))
print('Running', ['python3', 'drake', '-j', jobs, '//check'])
if subprocess.call(['python3', 'drake', '-j', jobs, '//check']) != 0:
  exit(1)
