#!/usr/bin/env python3

import infinit.beyond.bottle

import unittest
import urllib.parse

from utils import *

from copy import deepcopy

with Beyond(create_delegate_user = False,
            force_admin = True) as beyond:

  class Test(unittest.TestCase):

    def test_do_not_exist(self):
      throws(lambda: beyond.get('users/castor'),
             404,
             json = False)

    def test_works(self):
      user = User()
      throws(lambda: beyond.get('users/%s' % user['name']),
             404,
             json = False)
      beyond.put('users/%s' % user['name'], json = user)
      user = beyond.get('users/%s' % user['name']).json()
      assertEq(user['name'], user['name'])
      assertEq(user['public_key'], user['public_key'])
      assert 'email' not in user
      users = beyond.get('users').json()
      assertEq(len(users['users']), 1)
      for k in ['name', 'public_key']:
        assertEq(users['users'][0][k], user[k])


  if __name__ == '__main__':
    unittest.main()
