#!/usr/bin/env python3

import infinit.beyond.bottle

import unittest

from utils import *

with Beyond() as beyond:

  class Test(unittest.TestCase):

    def test_confirm(self):
      emailer = Emailer()
      user = User()
      beyond.emailer = emailer
      user.put(beyond)
      assert 'User/Welcome' in emailer.get(user['email'])
      assert 'Sales/New Customer' in emailer.get('sales@infinit.sh')
      welcome = emailer.get_specifics(user['email'], 'User/Welcome').pop()
      sales = emailer.get_specifics('sales@infinit.sh', 'Sales/New Customer').pop()
      assertEq(welcome['name'], sales['user']['name'])
      assertEq(welcome['email'], sales['user']['email'])

  if __name__ == '__main__':
    unittest.main()
