#!/usr/bin/env python3

import os
import sys
sys.path.insert(0, '%s/../../elle/drake/src' % os.path.dirname(__file__))

import drake
import drake.cxx

tk = drake.cxx.GccToolkit('clang++')

cfg = drake.cxx.Config()
cfg.enable_debug_symbols()
cfg.enable_optimization()

with drake.Drake('../..') as d:
  d.run(
    python = '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/',
    cxx_toolkit = tk,
    cxx_config = cfg,
  )
