#!/usr/bin/env python3

import infinit.beyond.bottle

import unittest
import urllib.parse

from utils import *

from copy import deepcopy

class Test(unittest.TestCase):

  def test_normal(self):
    with Beyond() as beyond:
      user = User()
      user.put(beyond)
      network = Network(name = 'server1-server2', owner = user)
      network.put(beyond)
      kvs = KeyValueStore(name = 'business', network = network)
      kvs.put(beyond)
      beyond.get('kvs/%s' % kvs['name'])
      beyond.delete('kvs/%s' % kvs['name'], auth = user)
      throws(lambda: beyond.get('kvs/%s' % kvs['name'],
                                json = False),
             404)

if __name__ == '__main__':
  unittest.main()
