#!/usr/bin/env python3

from utils import *
import json

with Infinit() as bob:
  assertEq(bob.run(['infinit', '--foo'], return_code = 2)[1],
           "./bin/infinit: command line error: unknown option: --foo\n"
           "Try './bin/infinit --help' for more information.\n")

  assertEq(bob.run(['infinit', 'foo'], return_code = 2)[1],
           "./bin/infinit: command line error: unknown object type: foo\n"
           "Try './bin/infinit --help' for more information.\n")

  assertEq(bob.run(['infinit', 'network', 'foo'], return_code = 2)[1],
           "./bin/infinit: command line error: unknown mode for object network: foo\n"
           "Try './bin/infinit network --help' for more information.\n")

  assertEq(bob.run(['infinit', 'network', '--foo'], return_code = 2)[1],
           "./bin/infinit: command line error: unknown option: --foo\n"
           "Try './bin/infinit network --help' for more information.\n")

  assertEq(bob.run(['infinit', 'network', 'list', '--foo'], return_code = 2)[1],
           "./bin/infinit: command line error: unknown option: --foo\n"
           "Try './bin/infinit network list --help' for more information.\n")

  assertEq(bob.run(['infinit', 'volume', 'create', 'name', '--network'], return_code = 2)[1],
           "./bin/infinit: command line error: option requires an argument: --network\n"
           "Try './bin/infinit volume create --help' for more information.\n")
  
