#!/usr/bin/env python3
from utils import *
import time

with Beyond() as beyond, Infinit(beyond = beyond) as bob, \
     Infinit(beyond = beyond) as alice:
  bob = User('bob', bob)
  alice = User('alice', alice)
  # Bob and Alice signup, then fetch other.
  bob.run('infinit-user --signup --name %s --email %s' % (
    bob.name, bob.name + '@infinit.io'))
  alice.run('infinit-user --signup --name %s --email %s' % (
    alice.name, alice.name + '@infinit.io'))
  bob.run('infinit-user --fetch --name %s' % alice.name)
  alice.run('infinit-user --fetch --name %s' % bob.name)

  # Bob create a local storage and a kelips network.
  bob.run('infinit-storage --create --name %s --filesystem' % bob.storage)
  bob.run('infinit-network --create --name %s --storage %s --kelips --k 1'
          ' --replication-factor 1 --push' % (bob.network, bob.storage))

  # Bob create a volume on the previous network, invite alice and run it.
  bob.run('infinit-volume --create --name %s --network %s --push' %
          (bob.volume, bob.network))
  bob.run('infinit-passport --create --as %s --user %s --network %s --push' %
          (bob.name, alice.name, bob.network))

  # Alice fetches bob's network, join it and run it.
  alice.run('infinit-network --fetch --name %s --as %s' %
            (bob.network, alice.name))
  alice.run('infinit-passport --fetch --as %s' % alice.name)
  alice.run('infinit-network --join --name %s' % bob.network)
  alice.run('infinit-volume --fetch --as %s' % alice.name)

  bob_volume = bob.async('infinit-volume --run --name %s --mountpoint %s --push --fetch' %
                         (bob.volume, bob.mountpoint))
  time.sleep(10)
  bob.run('infinit-acl --set --user %s --mode rw --enable-inherit --path %s' % (alice.name, bob.mountpoint))

  alice_volume = alice.async('infinit-volume --run --name %s --mountpoint %s --fetch' %
              (bob.volume, alice.mountpoint))
  time.sleep(10)

  # FIXME: This test fails @ line 34.
