#!/usr/bin/env python3

from utils import *

with Infinit() as bob:
  bob.run(['infinit-user', '--compatibility-version', '1.0.0',
           '--version'])
  bob.run(['infinit-user', '--compatibility-version', '2.1',
           '--version'])
  bob.run(['infinit-user', '--compatibility-version', '3',
           '--version'])
  try:
    bob.run(['infinit-user',  '--compatibility-version', '1..'])
  except Exception as e:
    pass
  try:
    bob.run(['infinit-user',  '--compatibility-version', ' '])
  except Exception as e:
    pass
  try:
    bob.run(['infinit-user',  '--compatibility-version', 'nekolas'])
  except Exception as e:
    pass
  try:
    bob.run(['infinit-user',  '--compatibility-version', '0..'])
  except Exception as e:
    pass
