#!/usr/bin/env python3

from utils import *

with Memo() as bob:
  bob.run(['user', 'create'])
  bob.run(['user', 'list',
           '--compatibility-version', '0.3.0'])
  bob.run(['user', 'list',
           '--compatibility-version', '0.5.2'])
  throws(lambda: bob.run(
    ['user', 'list', '--compatibility-version', '0.119.0']))
  throws(lambda: bob.run(
    ['user', 'list', '--compatibility-version', '1..']))
  throws(lambda: bob.run(
    ['user', 'list', '--compatibility-version', ' ']))
  throws(lambda: bob.run(
    ['user', 'list', '--compatibility-version', 'nekolas']))
  throws(lambda: bob.run(
    ['user', 'list', '--compatibility-version', '0..']))
