#!/usr/bin/env python3

from utils import *
import json

with_kvs = os.environ.get('TEST_MEMO_WITH_KVS', '1') == '1'

# Creating and deleting networks locally.
with Beyond() as beyond, Memo(beyond = beyond) as bob, \
     Memo(beyond = beyond) as alice:
  bob.run(['user', 'create',  'bob'])
  alice.run(['user', 'create',  'alice'])

  try:
    bob.run(['network', 'delete', 'broken', '--as', 'bob', '--unlink'])
    unreachable()
  except Exception as e:
    pass
  bob.run(['network', 'create', 'broken', '--as', 'bob'])
  # Check descriptor is created.
  assertEq(len(os.listdir(bob.networks_path)), 1)
  # Check network is linked.
  assertEq(len(os.listdir(bob.linked_networks_path)), 1)
  bob.run(['network', 'run', '--name', 'broken',
           '--as', 'bob', '--async', '--cache', '-s'],
          timeout = 2, kill = True)
  # Ensure network cache directory is created
  assertEq(len(os.listdir('%s/cache/bob/bob/broken' % bob.state_path)), 2)
  bob.run(['network', 'delete', '--name', 'broken', '--as', 'bob',
           '--unlink'])
  # Ensure network cache directory is removed
  assertEq(len(os.listdir('%s/cache/bob' % bob.state_path)), 0)

  bob.run(['network', 'create', 'broken', '--as', 'bob'])
  bob.run(['network', 'run', '--name', 'broken', '--as', 'bob',
           '--async', '--cache', '-s'],
          timeout = 2, kill = True)
  assertEq(len(os.listdir('%s/cache/bob/bob/broken' % bob.state_path)), 2)
  # Specified.
  bob.run(
    ['network', 'delete', 'bob/broken', '--as', 'bob', '--unlink'])
  assertEq(len(os.listdir('%s/cache/bob' % bob.state_path)), 0)
  bob.run(
    ['network', 'create', '--name', 'osef', '--as', 'bob'])
  net = bob.run_json(
    ['network', 'export', '--name', 'osef', '--as', 'bob'])
  alice.run(['network', 'import'], input = net)
  try:
    alice.run(['network', 'delete',
               '--name', 'osef', '--as', 'alice'])
    unreachable()
  except Exception as e:
    pass
  alice.run(['network', 'delete',
             '--name', 'bob/osef', '--as', 'alice', '--unlink'])

# Unlinking
with Memo() as tmp:
  bob = User(name = 'bob', memo = tmp)
  bob.run(['user', 'create'])
  bob.run(['silo', 'create', 'filesystem', 's'])
  bob.run(['network', 'create', 'n', '--silo', 's'])
  # Check descriptor is created.
  assertEq(len(os.listdir(bob.memo.networks_path)), 1)
  # Check network is linked.
  assertEq(len(os.listdir(bob.memo.linked_networks_path)), 1)
  print(os.listdir(bob.memo.networks_path))
  # Store descriptor.
  descriptor = None
  with open('%s/bob/n' % bob.memo.networks_path) as f:
    descriptor = f.read()
  # Store linked network.
  linked_net = None
  with open('%s/bob/bob/n' % bob.memo.linked_networks_path, 'r') as f:
    linked_net = f.read()
  bob.run(['network', 'run', 'n', '-s', '--async', '--cache'],
          timeout = 2, kill = True)
  # Ensure cache directories created.
  assertEq(len(os.listdir('%s/cache/bob/bob/n' % bob.memo.state_path)), 2)
  bob.run(['network', 'unlink', 'n'])
  # Ensure cache directories removed.
  assertEq(len(os.listdir('%s/cache/bob' % bob.memo.state_path)), 0)
  # Check network is no longer linked.
  assertEq(len(os.listdir('%s/bob/bob' % bob.memo.linked_networks_path)), 0)
  # Check network descriptor still exists.
  assertEq(len(os.listdir(bob.memo.networks_path)), 1)
  bob.run(['network', 'delete', 'n'])
  assertEq(len(os.listdir('%s/bob' % bob.memo.networks_path)), 0)
  # Simulate old link behaviour: copy linked network to descriptor folder,
  # check that unlink changes it to a network descriptor.
  with open('%s/bob/n' % bob.memo.networks_path, 'w') as f:
    f.write(linked_net)
  assertEq(len(os.listdir(bob.memo.networks_path)), 1)
  node_id = json.loads(linked_net)['model']['id']
  assertEq(len(node_id), 44)
  out, _ = bob.run(['network', 'unlink', 'n'])
  assert node_id in out
  assertEq(len(os.listdir(bob.memo.networks_path)), 1)
  with open('%s/bob/n' % bob.memo.networks_path) as f:
    test = f.read()
    assertEq(test, descriptor)
  bob.run(['network', 'link', 'n', '--node-id', node_id])
  with open('%s/bob/bob/n' % bob.memo.linked_networks_path, 'r') as f:
    relinked_net = f.read()
    assertEq(node_id, json.loads(relinked_net)['model']['id'])

# Fetch & list.
with Beyond() as beyond, Memo(beyond = beyond) as bob, \
     Memo(beyond = beyond) as alice:

  bob.run(['user', 'signup', '--name', 'bob', '--email', 'bob@infinit.io'])
  alice.run(['user', 'signup', '--name', 'alice', '--email', 'alice@infinit.io'])
  bob.run(['user', 'fetch', '--name', 'alice'])
  alice.run(['user', 'fetch', '--name', 'bob'])

  # Create.
  l = bob.run_json(['network', 'list', '--as', 'bob', '--script'])
  assertEq(len(l), 0)
  bob.run(['network', 'create', '--name', 'a', '--as', 'bob', '--push',
          '--description', 'some network'])
  try:
    bob.run(['network', 'push', '--name', 'a', '--as', 'not_bob'])
    unreachable()
  except Exception as e:
    pass
  l = bob.run_json(['network', 'list', '--script', '--as', 'bob'])
  assertEq(len(l), 1)
  n = bob.run_json(['network', 'export', '--as', 'bob', 'a'])
  assertEq(n['description'], 'some network')
  bob.run(['network', 'create', '--name', 'b', '--as', 'bob', '--push'])
  l = bob.run_json(['network', 'list', '--script', '--as', 'bob'])
  assertEq(len(l), 2)

  l = alice.run_json(['network', 'list', '--script', '--as', 'alice'])
  assertEq(len(l), 0)
  alice.run(['network', 'fetch', '--name', 'bob/a', '--as', 'alice'])
  l = alice.run_json(['network', 'list', '--script', '--as', 'alice'])
  assertEq(len(l), 1)
  n = alice.run_json(['network', 'export', '--as', 'alice', 'bob/a'])
  assertEq(n['description'], 'some network')
  alice.run(['network', 'fetch', '--as', 'alice'])
  # Still one, alice hasn't been invited to the 2nd network.
  l = alice.run_json(['network', 'list', '--script', '--as', 'alice'])
  assertEq(len(l), 1)
  # Check that listing moves linked networks.
  bob_n, _ = bob.run(['network', 'create', 'bob-linked', '--as', 'bob',
                      '--output', '-'])
  assert not os.path.exists('%s/bob/bob/bob-linked' % bob.linked_networks_path)
  with open('%s/bob/bob-linked' % bob.networks_path, 'w') as f:
    f.write(bob_n)
  bob.run(['network', 'list', '--as', 'bob'])
  with open('%s/bob/bob/bob-linked' % bob.linked_networks_path) as f:
    test = f.read()
    assertEq(json.loads(test), json.loads(bob_n))

# Update network.
with Beyond() as beyond, Memo(beyond = beyond) as bob, \
     Memo(beyond = beyond) as alice:
  bob.run(['user', 'signup',  'bob', '--email', 'bob@infinit.io'])
  alice.run(['user', 'signup',  'alice', '--email', 'alice@infinit.io'])
  bob.run(['user', 'fetch', '--name', 'alice'])

  bob.run(['network', 'create', '--name', 'n',
           '--as', 'bob', '--kelips', '--push', '--port', '8181'])
  bob.run(['passport', 'create', '--push', '--network', 'n', '--user', 'alice', '--as', 'bob'])
  alice.run(['passport', 'fetch', '--as', 'alice'])

  alice.run(['network', 'fetch', '--name', 'bob/n', '--as', 'alice'])
  alice.run(['network', 'link', '--name', 'bob/n', '--as', 'alice'])
  # Make sure you can only link once.
  throws(lambda: alice.run(['network', 'link', '--name', 'bob/n', '--as', 'alice']))
  e0 = alice.run_json(['network', 'export', '--name', 'bob/n', '--as', 'alice'])
  new_version = '0.3.0'
  assertEq(e0.get('description'), None)
  bob.run(['network', 'update', '--name', 'n',
           '--compatibility-version', new_version,
           '--as', 'bob',
           '--push',
           '--protocol', 'tcp',
           '--description', 'some network'])
  alice.run(['network', 'fetch', '--name', 'bob/n', '--as', 'alice'])
  e1 = alice.run_json(['network', 'export', '--name', 'bob/n', '--as', 'alice'])
  print(e1)
  assertEq(e1['description'], 'some network')
  assertNeq(e0['version'], e1['version'])
  assertEq(e1['version'], new_version)
  assertEq(e1['overlay']['rpc_protocol'], 'tcp')
  del e0['version']
  del e1['version']
  del e1['description']
  del e0['overlay']['rpc_protocol']
  del e1['overlay']['rpc_protocol']
  assertEq(e0, e1)

def setup(beyond, bob, alice):
  bob.run(['user', 'signup',  'bob', '--email', 'bob@infinit.io'])
  alice.run(['user', 'signup',  'alice', '--email', 'alice@infinit.io'])
  bob.run(['user', 'fetch', '--name', 'alice'])
  # Create network.
  bob.run(['network', 'create', '--name', 'n', '--as', 'bob', '--kelips', '--push', '--port', '8181', '--protocol', 'utp'])
  bob.run(['passport', 'create', '--push', '--network', 'n', '--user', 'alice', '--as', 'bob'])
  # Fetch networks & passports.
  alice.run(['network', 'fetch', '--name', 'bob/n', '--as', 'alice'])
  alice.run(['passport', 'fetch', '--as', 'alice'])

# Make sure passports are kept after updating.
with Beyond() as beyond, Memo(beyond = beyond) as bob, \
     Memo(beyond = beyond) as alice:
  setup(beyond, bob, alice)
  assertEq(len(alice.run_json(['passport', 'list',
                               '--as', 'alice', '--script'])),
           1)
  alice.run(['passport', 'delete', '--user', 'alice', '--network', 'bob/n', '--as', 'alice'])
  assertEq(len(alice.run_json(['passport', 'list', '--as', 'alice', '--script'])),
           0)
  bob.run(['network', 'update', '--name', 'n', '--compatibility-version', '0.3.0', '--as', 'bob', '--push'])
  alice.run(['passport', 'fetch', '--as', 'alice'])
  assertEq(len(alice.run_json(['passport', 'list',
                               '--as', 'alice', '--script'])),
           1)

# Make sure endpoints and stats are kept after updating.
for field, body in [
    ('stat', {'capacity': 100, 'usage': 1000}),
    ('endpoints', {'stuff':  [{'host': '127.0.0.1', 'port': 8080}]})
]:
  with Beyond(disable_authentication = True) as beyond, Memo(beyond = beyond) as bob, \
       Memo(beyond = beyond) as alice:
    setup(beyond, bob, alice)
    # Bypass the binaries.
    import requests
    requests.put(
      '%s/networks/bob/n/%s/alice/node' % (beyond.domain, field),
      headers = {
        'Content-Type': 'application/json',
      },
      data = json.dumps(body)).raise_for_status()
    initial_res = requests.get(
      '%s/networks/bob/n/%s' % (beyond.domain, field),
      headers = {
        'Content-Type': 'application/json',
      }).json()
    if field == 'endpoints':
      assertIn('alice', initial_res)
    else:
      assertIn('usage', initial_res)
      assertIn('capacity', initial_res)
    bob.run(['network', 'update',
             '--name', 'n',
             '--compatibility-version', '0.5.2',
             '--as', 'bob',
             '--push'])
    res = requests.get(
      '%s/networks/bob/n/%s' % (beyond.domain, field),
      headers = {
        'Content-Type': 'application/json',
      }).json()
    assertEq(res, initial_res)

# Create and link with multiple 'storage'.
with Beyond() as beyond, Memo(beyond = beyond) as bob, \
     Memo(beyond = beyond) as alice:
  bob.run(['user', 'signup',  'bob', '--email', 'bob@infinit.io'])
  alice.run(['user', 'signup',  'alice',
             '--email', 'alice@infinit.io'])
  bob.run(['user', 'fetch', '--name', 'alice'])
  bob.run(['silo', 'create', 'filesystem',
           '--name', 'bob_storage_1'])
  bob.run(['silo', 'create', 'filesystem',
           '--name', 'bob_storage_2'])
  bob.run(['network', 'create', '--name', 'n', '--as', 'bob',
           '--kelips', '--push',
           '--silo', 'bob_storage_1', '--silo', 'bob_storage_2'])
  s1 = bob.run(['network', 'list-silos', '--name', 'bob/n',
                '--as', 'bob'])
  bob.run(['passport', 'create', '--push', '--network', 'n',
           '--user', 'alice', '--as', 'bob'])
  alice.run(['passport', 'fetch', '--as', 'alice'])

  alice.run(['network', 'fetch', '--name', 'bob/n', '--as', 'alice'])
  alice.run(['silo', 'create', 'filesystem', 'alice_storage_1'])
  alice.run(['silo', 'create', 'filesystem', 'alice_storage_2'])
  alice.run(['network', 'link', '--name', 'bob/n', '--as', 'alice',
             '--silo', 'alice_storage_1', '--silo', 'alice_storage_2'])
  s2 = alice.run(['network', 'list-silos', '--name', 'bob/n',
                  '--as', 'alice'])
  assertEq(len(s1), 2)
  assertEq(len(s2), 2)

# Pull and delete.
with Beyond() as beyond, Memo(beyond = beyond) as bob:
  # Local and Beyond.
  bob.run(['user', 'signup', 'bob', '--email', 'bob@infinit.io'])
  bob.run(['network', 'create', '--as', 'bob', 'n', '--push'])
  bob.run(['network', 'run', '--name', 'n', '--as', 'bob',
           '--async', '--cache', '-s'],
          timeout = 2, kill = True)
  assertEq(len(os.listdir('%s/cache/bob/bob/n' % bob.state_path)), 2)
  bob.run(['network', 'delete', '--as', 'bob', 'n', '--unlink'])
  assertEq(len(os.listdir('%s/cache/bob' % bob.state_path)), 0)
  bob.run(['network', 'fetch', '--as', 'bob', 'n'])
  assertEq(len(bob.run_json(['network', 'list', '--as', 'bob', '-s'])), 1)
  bob.run(['network', 'delete', '--as', 'bob', 'n', '--pull', '--unlink'])
  assertEq(len(bob.run_json(['network', 'list', '--as', 'bob', '-s'])), 0)
  bob.run(['network', 'fetch', '--as', 'bob', 'n'], return_code = 1)
  # Only local.
  bob.run(['network', 'create', '--as', 'bob', 'n2'])
  assertEq(len(bob.run_json(['network', 'list', '--as', 'bob', '-s'])), 1)
  bob.run(['network', 'delete', '--as', 'bob', 'n2', '--pull', '--unlink'])
  assertEq(len(bob.run_json(['network', 'list', '--as', 'bob', '-s'])), 0)

# Delete multi user.
def remove_network_linked_by_two_users(owner_remove = True):
  with Beyond() as beyond, Memo(beyond = beyond) as memo:
    owner = User('bob', memo)
    invitee = User('alice', memo)
    owner.run('user signup --email owner@infinit.sh ' + owner.name)
    invitee.run('user signup --email invitee@infinit.sh ' + invitee.name)
    owner.run('network create n --push')
    owner.run(['network', 'run', '--name', 'n',
               '--async', '--cache', '-s'],
              timeout = 2, kill = True)
    assertEq(len(os.listdir('%(state)s/cache/%(user_name)s/%(owner_name)s/n' % {
      'state': memo.state_path,
      'user_name': owner.name,
      'owner_name': owner.name})), 2)
    assertEq(
      owner.run_json('network list --script'),
      [
        {'name': '%s/n' % owner.name, 'linked': True}
      ])
    owner.run('passport create --network n --push --user ' + invitee.name)
    invitee.run('passport fetch')
    invitee.run('network fetch')
    assertEq(
      owner.run_json('network list --script'),
      [
        {'name': '%s/n' % owner.name, 'linked': True}
      ])
    assertEq(
      invitee.run_json('network list --script'),
      [
        {'name': '%s/n' % owner.name, 'linked': False}
      ])
    invitee.run('network link --name %s/n' % owner.name)
    invitee.run(['network', 'run', '--name', '%s/n' % owner.name,
                 '--async', '--cache', '-s'],
                timeout = 2, kill = True)
    assertEq(len(os.listdir('%(state)s/cache/%(user_name)s/%(owner_name)s/n' % {
      'state': memo.state_path,
      'user_name': invitee.name,
      'owner_name': owner.name})), 2)
    assertEq(
      invitee.run_json('network list --script'),
      [
        {'name': '%s/n' % owner.name, 'linked': True}
      ])
    invitee.run('network unlink --name %s/n' % owner.name)
    assertEq(len(os.listdir('%(state)s/cache/%(name)s' % {
      'state': memo.state_path, 'name': invitee.name})), 0)
    assertEq(
      invitee.run_json('network list --script'),
      [
        {'name': '%s/n' % owner.name, 'linked': False}
      ])
    invitee.run('network link --name %s/n' % owner.name)
    invitee.run(['network', 'run', '--name', '%s/n' % owner.name,
                 '--async', '--cache', '-s'],
                timeout = 2, kill = True)
    assertEq(len(os.listdir('%(state)s/cache/%(user_name)s/%(owner_name)s/n' % {
      'state': memo.state_path,
      'user_name': invitee.name,
      'owner_name': owner.name})), 2)
    if owner_remove:
      throws(lambda: owner.run('network delete n'))
      owner.run('network delete n --unlink')
    else:
      throws(lambda: invitee.run('network delete %s/n' % owner.name ))
      invitee.run('network delete %s/n --unlink' % owner.name)
    assertEq(owner.run_json('network list --script'), [])
    assertEq(invitee.run_json('network list --script'), [])
    assertEq(len(os.listdir('%(state)s/cache/%(name)s' % {
      'state': memo.state_path, 'name': owner.name})), 0)
    assertEq(len(os.listdir('%(state)s/cache/%(name)s' % {
      'state': memo.state_path, 'name': invitee.name})), 0)

remove_network_linked_by_two_users(owner_remove = True)
remove_network_linked_by_two_users(owner_remove = False)

# Purge.
with Beyond() as beyond, \
    Memo(beyond = beyond) as bob, Memo(beyond = beyond) as alice:
  bob.run(['user', 'signup', 'bob', '--email', 'bob@infinit.io'])
  alice.run(
    ['user', 'signup', 'alice', '--email', 'alice@infinit.io'])
  bob.run(['silo', 'create', 'filesystem', '--as', 'bob', 's'])
  bob.run(['network', 'create', '--as', 'bob', 'n', '-S', 's', '-p'])
  assertEq(len(bob.run_json(['network', 'list', '-s', '--as', 'bob'])), 1)
  bob.run(['network', 'run', '--name', 'n', '--as', 'bob',
           '--async', '--cache', '-s'],
          timeout = 2, kill = True)
  assertEq(len(os.listdir('%s/cache/bob/bob/n' % bob.state_path)), 2)
  bob.run(['user', 'fetch', 'alice'])
  bob.run(['passport', 'create', '--as', 'bob',
           '-u', 'alice', '-N', 'n', '-p'])
  assertEq(len(bob.run_json(['passport', 'list', '-s', '--as', 'bob'])), 1)
  alice.run(['network', 'create', '--as', 'alice', 'n', '-p'])
  alice.run(['network', 'run', '--name', 'n', '--as', 'alice',
             '--async', '--cache', '-s'],
            timeout = 2, kill = True)
  assertEq(len(os.listdir('%s/cache/alice/alice/n' % alice.state_path)), 2)
  alice.run(['user', 'fetch', 'bob'])
  alice.run(['passport', 'create', '--as', 'alice',
           '-u', 'bob', '-N', 'n', '-p'])
  bob.run(['passport', 'fetch', '--as', 'bob'])
  assertEq(len(bob.run_json(['passport', 'list', '-s', '--as', 'bob'])), 2)
  if with_kvs:
    bob.run(['kvs', 'create', '--as', 'bob', 'k', '-N', 'n', '-p'])
    assertEq(len(bob.run_json(['kvs', 'list', '-s', '--as', 'bob'])), 1)
  bob.run(['network', 'delete', 'n', '--as', 'bob',
           '--purge', '--pull', '--unlink'])
  assertEq(len(bob.run_json(['network', 'list', '-s', '--as', 'bob'])), 0)
  assertEq(len(bob.run_json(['passport', 'list', '-s', '--as', 'bob'])), 1)
  if with_kvs:
    assertEq(len(bob.run_json(['kvs', 'list', '-s'])), 0)
  assertEq(len(os.listdir('%s/cache/bob' % bob.state_path)), 0)
  bob.run(['network', 'fetch', '--as', 'bob', 'n'], return_code = 1)
  alice.run(['passport', 'fetch', '--as', 'alice', '-N', 'bob/n'],
            return_code = 1)
