#!/usr/bin/env python3

from utils import *
import json

# Using hub to retreive passports.
with Beyond() as beyond, Infinit(beyond) as bob, Infinit(beyond) as alice:
  bob.run(['infinit-user', '--signup',
           '--name', 'bob', '--email', 'bob@infinit.io'])
  alice.run(['infinit-user', '--signup',
             '--name', 'alice', '--email', 'alice@infinit.io',
           ])
  alice.run(['infinit-passport', '--fetch', '--as', 'alice'])
  bob.run(['infinit-user', '--fetch',
           '--name', 'alice'])
  networks = set()
  for i in range(10):
    network = 'network%r' % i
    networks.add('bob/%s' % network)
    bob.run(['infinit-network', '--create', '--push',
             '--name', network,
             '--as', 'bob'])
    bob.run(['infinit-passport', '--create', '--push',
             '--network', network,
             '--user', 'alice',
             '--as', 'bob'])
  alice.run(['infinit-passport', '--fetch', '--as', 'alice'])
  l = set(p['network'] for p in alice.run_json(
    ['infinit-passport', '--list', '--as', 'alice', '--script']))
  assertEq(l, networks)
  for network in networks:
    alice.run(['infinit-network', '--fetch',
               '--name', network,
               '--as', 'alice'])
  for network in networks:
    try:
      alice.run(['infinit-network', '--run',
                 '--name', network,
                 '--as', 'alice'])
      unreachable()
    except Exception as e:
      assert 'this device is not yet linked to the network' in e.args[0]
  for network in networks:
    alice.run(['infinit-network', '--link',
               '--name', network,
               '--as', 'alice'])

# Storing more than x passports.
limit = 2
with Beyond(beyond_args = {'limits': {'networks': {'passports': limit}}}) as beyond, Infinit(beyond) as bob:
  bob.run(['infinit-user', '--signup',
           '--name', 'bob', '--email', 'bob@infinit.io'])
  bob.run(['infinit-network', '--create', '--push',
           '--name', 'network',
           '--as', 'bob'])
  def push_passport(i):
    user = Infinit(beyond)
    user.__enter__()
    name = 'invitee%d' % i
    try:
      user.run(['infinit-user', '--signup',
                '--name', name, '--email', '%s@infinit.io' % name])
      bob.run(['infinit-user', '--fetch', '--as', 'bob', '--name', name])
      return bob.run(['infinit-passport', '--create', '--push',
                      '--network', 'network',
                      '--user', name,
                      '--as', 'bob'])
    finally:
      user.__exit__()
  for i in range(0, limit):
    push_passport(i)
  try:
    push_passport(limit)
    unreachable()
  except Exception as e:
    assert 'sales@infinit.sh' in e.args[0]
    assert 'Payment Required' in e.args[0]

# Pull and delete
with Beyond() as beyond, \
    Infinit(beyond = beyond) as bob, \
    Infinit(beyond = beyond) as alice:
  bob.run(['infinit-user', '--signup', 'bob', '--email', 'b@infinit.io'])
  alice.run(['infinit-user', '--signup', 'alice', '--email', 'a@infinit.io'])
  bob.run(['infinit-network', '--create', '--as', 'bob', 'n', '--push'])
  bob.run(['infinit-user', '--fetch', 'alice'])
  bob.run(['infinit-passport', '--create', '--as', 'bob',
           '-u', 'alice', '-n', 'n', '--push'])
  alice.run(['infinit-network', '--fetch', '--as', 'alice', 'bob/n'])
  alice.run(['infinit-passport', '--fetch', '--as', 'alice'])
  assertEq(len(alice.run_json(['infinit-passport', '--list', '-s'])), 1)
  # Local and Beyond.
  bob.run(['infinit-passport', '--delete', '--as', 'bob',
           '-u', 'alice', '-n', 'n', '--pull'])
  assertEq(len(bob.run_json(['infinit-passport', '--list', '-s'])), 0)
  # Local only.
  alice.run(['infinit-passport', '--delete', '--as', 'alice',
             '-u', 'alice', '-n', 'bob/n', '--pull'])
  assertEq(len(alice.run_json(['infinit-passport', '--list', '-s'])), 0)
  alice.run(['infinit-passport', '--fetch', '--as', 'alice',
             '-u', 'alice', '-n', 'n'], return_code = 1)
