#!/usr/bin/env python3

import base64
import threading

from itertools import *
from utils import *

def initialize(memos):
  # Create users and storage
  for i in memos:
    i.env['ELLE_LOG_FILE'] = '%s/logs' % i.dir
    i.env['ELLE_LOG_TIME'] = '1'
    i.env['ELLE_LOG_LEVEL'] = ','.join(
      '%s:DEBUG' % c for c in [
        'infinit.model*',
        'infinit.overlay*',
      ])
    i.env['MEMO_USER'] = i.user
    i.run(['user', 'create'])
    i.run(['storage',
           'create', 'storage', '--filesystem',
           '--path', '%s/blocks' % i.dir])
  # Exchange users
  for (lhs, rhs) in permutations(memos, 2):
    user, _ = rhs.run(['user', 'export'])
    lhs.run(['user', 'import'], input = user)
  # Create network and volume, distribute passports and link
  a = memos[0]
  a.run(['network', 'create', 'network', '--kelips',
         '--replication-factor', '3',
         '--eviction-delay', '1s',
         '--kelips-contact-timeout', '3s',
         '--silo', 'storage'])
  network, _ = a.run(['network', 'export', 'network'])
  a.run(['volume',
         '--create', 'volume', '--network', 'network'])
  volume, _ = a.run(['volume', 'export', 'volume'])
  for i in memos[1:]:
    i.run(['network', 'import'], input = network)
    i.run(['volume', 'import'], input = volume)
    a.run(['passport',
           'create', '--network', 'network',
           '--user', i.user])
    p, _ = a.run(['passport',
                  '--export', '--network', 'network',
                  '--user', i.user])
    i.run(['passport', 'import'], input = p)
    i.run(['network','link', 'a/network', '--silo', 'storage'])

def run(*memos):
  def wait_file(path):
    while True:
      try:
        if os.stat(path).st_size > 0:
          break
      except FileNotFoundError:
        time.sleep(0.1)
  run_a = memos[0].spawn(
    ['volume',
     '--run', 'a/volume', '--script', '--allow-root-creation',
     '--endpoints-file', '%s/endpoints' % memos[0].dir])
  wait_file('%s/endpoints' % memos[0].dir)
  # FIXME: use a deterministic way to ensure first node is up.
  time.sleep(5)
  res = [run_a]
  peers = ['--peer', '%s/endpoints' % memos[0].dir]
  for i in memos[1:]:
    res.append(i.spawn(
      ['network',
       '--run', 'a/network', '--script',
       '--endpoints-file', '%s/endpoints' % i.dir] + peers))
    wait_file('%s/endpoints' % i.dir)
    # FIXME: use a deterministic way to ensure node is up.
    time.sleep(2)
    peers += ['--peer', '%s/endpoints' % i.dir]
  return tuple(res)

def create_file(infinit):
  def op(p, j):
    j = json.dumps(j)
    p.stdin.write((j + '\n').encode())
    p.stdin.flush()
    output = next(p.stdout)
    return json.loads(output.decode())
  op(infinit, {'operation': 'create', 'path': '/foo',
             'handle': 'h', 'flags': 0x0202, 'mode': 33206})
  contents = bytes(16385)
  op(infinit, {
    'operation': 'write',
    'handle': 'h',
    'offset': 0,
    'size': len(contents),
    'content': base64.b64encode(contents).decode('latin-1')})

def wait(run):
  terminated = False
  try:
    out, err = run.communicate(timeout = 30)
    rv = run.wait()
    terminated = True
    if rv != 0:
      reason = 'process (%s) failed with return code %s' % (run.user, rv)
      print(reason, file = sys.stderr)
      print('STDOUT:\n%s' % out.decode('utf-8'))
      print('STDERR:\n%s' % err.decode('utf-8'))
      raise Exception(reason)
  except Exception as e:
    print('unable to terminate: %s' % e)
    pass
  finally:
    if not terminated:
      run.kill()

# Test that killing a node and adding a new one rebalances the blocks to the new
# node.
def test_a():
  with Memo(user = 'a') as a,                    \
       Memo(user = 'b') as b,                    \
       Memo(user = 'c') as d,                    \
       Memo(user = 'd') as c:
    memos = [a, b, c, d]
    initialize(memos)
    # Run volume with A, B and C
    run_a, run_b, run_c = run(a, b, c)
    # Create file
    create_file(run_a)
    # Check blocks are replicated
    def blocks(i):
      return list(chain(*(
        files for d, subd, files in os.walk('%s/blocks' % i.dir))))
    assertEq(blocks(a), blocks(b))
    assertEq(blocks(a), blocks(c))
    # Kill C, plug D
    run_c.terminate()
    wait(run_c)
    run_d = d.spawn(['network',
                     '--run', 'a/network', '--script',
                     '--peer', '%s/endpoints' % a.dir,
                     '--peer', '%s/endpoints' % b.dir])
    # Wait for rebalancing
    blocks_a = blocks(a)
    attempts = 0
    print('all blocks: %s' % blocks_a)
    while True:
      blocks_d = blocks(d)
      print('new node\'s blocks: %s' % blocks_d)
      if blocks_d == blocks_a:
        break
      time.sleep(1)
      attempts += 1
      if attempts > 120:
        raise Exception('%s blocks failed to be rebalanced' %
                        (len(blocks_a) - len(blocks_d)))
    wait(run_a)
    run_b.terminate()
    wait(run_b)
    run_d.terminate()
    wait(run_d)

# Check that when there are 4 nodes and a replication factor of 3, killing 1
# node rebalances its blocks to the remaining nodes.
def test_b():
  with Memo(user = 'a') as a,                    \
       Memo(user = 'b') as b,                    \
       Memo(user = 'c') as d,                    \
       Memo(user = 'd') as c:
    memos = [a, b, c, d]
    initialize(memos)
    # Run volume with A, B and C
    run_a, run_b, run_c, run_d = run(a, b, c, d)
    # FIXME: use a deterministic way to wait until D is connected.
    time.sleep(5)
    # Create file
    create_file(run_a)
    # Check blocks are replicated
    def check_replication(memos):
      blocks = {}
      for i in memos:
        for block in chain(*(
            files for d, subd, files in os.walk('%s/blocks' % i.dir))):
          blocks.setdefault(block, 0)
          blocks[block] += 1
      print(blocks)
      for block, value in blocks.items():
        if value != 3:
          return False
      return True
    assert check_replication(memos)
    # Kill D
    run_d.terminate()
    wait(run_d)
    # Wait for rebalancing
    attempt = 0
    while not check_replication([a, b, c]):
      time.sleep(1)
      attempt += 1
      if attempt > 120:
        raise Exception('some block were not replicated')
    wait(run_a)
    run_b.terminate()
    wait(run_b)
    run_c.terminate()
    wait(run_c)

test_a()
test_b()
