#!/usr/bin/env python3

import re
from utils import *
from math import *

def static_vars(**kwargs):
  def decorate(func):
    for k in kwargs:
      setattr(func, k, kwargs[k])
    return func
  return decorate

B = 1
kB = 1000 ** 1
MB = 1000 ** 2
GB = 1000 ** 3
TB = 1000 ** 4
KiB = 2 ** 10
MiB = 2 ** 20
GiB = 2 ** 30
TiB = 2 ** 40

units = {'kb': kB, 'kib': KiB, 'Kib': KiB, 'KiB': KiB,
         'mb': MB, 'mib': MiB, 'Mib': MiB, 'MiB': MiB,
         'gb': GB, 'gib': GiB, 'Gib': GiB, 'GiB': GiB,
         'tb': TB, 'tib': TiB, 'Tib': TiB, 'TiB': TiB,
         'b': B, 'B': B, '': B}

def unformat(s):
  '''Decode capacity with units into an (integral...) number of bytes
  (e.g., `"10KiB"` => `10240`).

  '''
  m = re.fullmatch(r'(.*?)([a-zA-Z]*)', s)
  size, unit = float(m.group(1)), m.group(2)
  return round(size * units[unit])


@static_vars(name = -1)
def test(memo, size, description = False):
  import json
  for unit in units:
    test.name += 1
    hsize = "%s%s" % (size, unit)
    args = [
      'silo', 'create', 'filesystem', str(test.name),
      '--capacity', hsize,
    ]
    if description:
      args += ['--description', 'some storage']
    memo.run(args)
    with open('%s/.local/share/infinit/memo/silos/%s' %
              (memo.dir, str(test.name)), 'r') as conf:
      j = json.loads(''.join(conf.readlines()))
      assertEq(j['capacity'], unformat(hsize))
      if description:
        assertEq(j['description'], 'some storage')
      else:
        assertEq(j.get('description', None), None)

with Memo() as bob:
  test(bob, '0', True)
  test(bob, '1', True)
  test(bob, '42')
  test(bob, '408')
  test(bob, '1024')
  test(bob, '101010')
  test(bob, '1010101')
  test(bob, '6.25')

# Purge.
with Beyond() as beyond, Memo(beyond = beyond) as tmp:
  bob = User(memo = tmp, name = 'bob')
  alice = User(memo = tmp, name = 'alice')
  bob.run(['user', 'signup', 'bob', '--email', 'bob@infinit.io'])
  alice.run(
    ['user', 'signup', 'alice', '--email', 'alice@infinit.io'])
  bob.run(['silo', 'create', 'filesystem', '--as', 'bob', 's'])
  assertEq(len(bob.run_json(['silo', 'list', '-s'])), 1)
  bob.run(['network', 'create', '--as', 'bob', 'n', '-S', 's', '-p'])
  assert os.path.exists('%s/bob/bob/n' % tmp.linked_networks_path)
  assertEq(len(bob.run_json(['network', 'list', '-s', '--as', 'bob'])), 1)
  bob.run(['passport', 'create', '--as', 'bob',
           '-u', 'alice', '-N', 'n'])
  alice.run(['network', 'link', '--as', 'alice', 'bob/n', '-S', 's'])
  assert os.path.exists('%s/alice/bob/n' % tmp.linked_networks_path)
  bob.run(['network', 'run', '--name', 'n', '--as', 'bob',
           '--async', '--cache', '-s'])
  assertEq(len(os.listdir('%s/cache/bob/bob/n' % tmp.state_path)), 2)
  bob.run(['silo', 'delete', 's', '--as', 'bob', '--purge'])
  assertEq(len(bob.run_json(['silo', 'list', '-s', '--as', 'bob'])), 0)
  # Ensure the descriptor is still there.
  assertEq(len(os.listdir(tmp.networks_path)), 1)
  # Ensure linked network has been removed.
  assert not os.path.exists('%s/bob/bob/n' % tmp.linked_networks_path)
  assert not os.path.exists('%s/alice/bob/n' % tmp.linked_networks_path)
  # Ensure network cache has been removed.
  assertEq(len(os.listdir('%s/cache/bob' % tmp.state_path)), 0)
