#!/usr/bin/env python3

from utils import *
import json

# Using hub to retreive a user.
with Beyond() as b, Infinit(beyond = b) as bob, Infinit(beyond = b) as alice:
  bob.run(['infinit-user', '--signup',
           '--name', 'bob', '--email', 'bob@infinit.io'])
  alice.run(['infinit-user', '--signup', '--full',
             '--name', 'alice', '--email', 'alice@infinit.io',
             '--password', 'loremipsword'])
  try:
    bob.run(['infinit-user', '--export', '--name', 'alice'])
    unreachable()
  except Exception as e:
    pass
  bob.run(['infinit-user', '--fetch', '--name', 'alice'])
  bob.run(['infinit-user', '--export', '--name', 'alice'])

## ----------------- ##
## Login / Push full ##
## ----------------- ##
# Using login.
with Beyond() as b, Infinit(beyond = b) as alice, Infinit(beyond = b) as alice2:
  alice.run(['infinit-user', '--signup', '--full',
             '--name', 'alice',
             '--email', 'alice@infinit.io',
             '--password', 'loremipsword'])
  alice_json = alice.run_json(
    ['infinit-user', '--export', '--name', 'alice', '--full'])
  alice2.run(['infinit-user', '--login',
              '--name', 'alice',
              '--password', 'loremipsword'])
  alice2_json = alice2.run_json(
    ['infinit-user', '--export', '--full', '--name', 'alice'])
  # XXX: Fix missing email.
  del alice_json['email']
  del alice2_json['email']
  assertEq(alice_json, alice2_json)

# Push --full.
with Beyond() as b, Infinit(beyond = b) as alice, Infinit(beyond = b) as alice2:
  alice.run(['infinit-user', '--create', '--name', 'alice'])
  alice.run(['infinit-user', '--push', '--full',
             '--name', 'alice',
             '--email', 'alice@infinit.io',
             '--password', 'loremipsword'])
  alice_json = alice.run_json(
    ['infinit-user', '--export', '--name', 'alice', '--full'])
  alice2.run(['infinit-user', '--login',
              '--name', 'alice',
              '--password', 'loremipsword'])
  alice2_json = alice2.run_json(
    ['infinit-user', '--export', '--full', '--name', 'alice'])
  # XXX: Fix missing email.
  # del alice_json['email']
  # del alice2_json['email']
  assertEq(alice_json, alice2_json)

# Push without --full.
with Beyond() as b, Infinit(beyond = b) as alice:
  alice.run(['infinit-user', '--create', '--name', 'alice'])
  alice.run(['infinit-user', '--push',
             '--name', 'alice',
             '--email', 'alice@infinit.io'])
  alice_json = alice.run_json(
    ['infinit-user', '--export', '--name', 'alice', '--full'])
  try:
    alice.run(['infinit-user', '--login', '--name', 'alice',
               '--password', 'loremipsword'])
    unreachable()
  except Exception as e:
    assertIn('doesn\'t use the hub to login', e.args[0])

# Read password from stdin (signup).
with Beyond() as b, Infinit(beyond = b) as alice, Infinit(beyond = b) as alice2:
  alice.run(['infinit-user', '--create', '--name', 'alice'])
  alice.run(['infinit-user', '--push',
             '--full',
             '--name', 'alice',
             '--email', 'alice@infinit.io'],
            input = 'loremipsword')
  alice2.run(['infinit-user', '--login',
              '--name', 'alice',
              '--password', 'loremipsword'])

# Read password from stdin (login).
with Beyond() as b, Infinit(beyond = b) as alice, Infinit(beyond = b) as alice2:
  alice.run(['infinit-user', '--create', '--name', 'alice'])
  alice.run(['infinit-user', '--push',
             '--full',
             '--name', 'alice',
             '--email', 'alice@infinit.io',
             '--password', 'loremipsword'])
  alice2.run(['infinit-user', '--login', '--name', 'alice'],
             input = 'loremipsword')

# Read password from stdin (both).
with Beyond() as beyond, TemporaryDirectory() as tmp,  \
     Infinit(beyond = beyond) as alice, Infinit(beyond = beyond) as alice2:
  alice.run(['infinit-user', '--create', '--name', 'alice'])
  alice.run(['infinit-user', '--push',
             '--full',
             '--name', 'alice',
             '--email', 'alice@infinit.io'],
            input = 'loremipsword')
  alice2.run(['infinit-user', '--login', '--name', 'alice'],
             input = 'loremipsword')

# Missing and invalid email.
with Beyond() as b, Infinit(beyond = b) as alice, Infinit(beyond = b) as alice2:
  try:
    alice.run(['infinit-user', '--signup', '--name', 'alice'])
    unreachable()
  except Exception as e:
    assertIn('(use --email)', e.args[0])
  try:
    alice.run(['infinit-user', '--signup', '--name', 'alice', '--email', 'foo@'])
    unreachable()
  except Exception as e:
    assertIn('invalid email address', e.args[0])
  # Create is not atomic, so 'alice' will be created after that.
  try:
    alice.run(['infinit-user', '--create', '--name', 'alice', '--push'])
    unreachable()
  except Exception as e:
    assertIn('(use --email)', e.args[0])

# Password missmatch.
with Beyond() as b, Infinit(beyond = b) as alice, Infinit(beyond = b) as alice2:
  alice.run(['infinit-user', '--signup', '--full',
             '--name', 'alice',
             '--email', 'alice@infinit.io',
             '--password', 'loremipsword'])
  try:
    alice2.run(['infinit-user', '--login',
                '--name', 'alice',
                '--password', 'not_password'])
    unreachable()
  except Exception as e:
    assertIn('password do not match', e.args[0])

# Pull a user that is not you.
with Beyond() as b, Infinit(beyond = b) as alice, Infinit(beyond = b) as bob:
  alice.run(['infinit-user', '--signup', '--full',
             '--name', 'alice',
             '--email', 'alice@infinit.io',
             '--password', 'loremipsword'])
  bob.run(['infinit-user', '--signup',
           '--name', 'bob',
           '--email', 'bob@infinit.io'])
  alice.run(['infinit-user', '--fetch', '--name', 'bob'])
  try:
    alice.run(['infinit-user', '--pull', '--as', 'bob'])
    unreachable()
  except Exception as e:
    assertIn('has no private key', e.args[0])

# Invalid user name.
with Beyond() as b, Infinit(beyond = b) as bob, Infinit(beyond = b) as alice:
  def create_with_name(name):
    bob.run(['infinit-user', '--create',
               '--name', name, '--email', '%s@infinit.io' % name])

  def create_with_name_throw(name):
    try:
      create_with_name(name)
      unreachable()
    except Exception as e:
      pass

  for name in ['bob', 'alice', 'eve_2', 'o', 'o2', 'first.last', 'first_last',
               'first-last', '_xxx_german_nickname_xxx_', '-dash', 'x' * 128,
               '2zio', '-lol-']:
    create_with_name(name)

  for name in ['Bob', 'accént', 'char+acter', 's/ash', '5tartWithADigit',
               '.start', '*', ' whitespace', '..', 'ру́сский', '汉语', 'にほん',
               'saṃskṛtam', 'it\'s', 'white space', '"ok"', 'o"k', 'x' * 129,
             ]:
    create_with_name_throw(name)

# Deleting users.
with Beyond() as b, Infinit(beyond = b) as alice:
  alice.run(['infinit-user', '--create', '--name', 'alice'])
  # Test prompt for deleting a user.
  alice.run(['infinit-user', '--create', '--name', 'bob'])
  try:
    alice.run(['infinit-user', '--delete', '--name', 'bob'], input = 'alice')
    unreachable()
  except Exception as e:
    pass
  alice.run(['infinit-user', '--delete', '--name', 'bob'], input = 'bob')
  # Test deleting user with --force and then deleting a user with only a public
  # key.
  alice.run(
    ['infinit-user', '--create', '--name', 'eve', '--email', 'eve@infinit.io'])
  alice.run(['infinit-user', '--push', '--name', 'eve'])
  alice.run(['infinit-user', '--delete', '--force', 'eve'])
  alice.run(['infinit-user', '--fetch', '--name', 'eve'])
  alice.run(['infinit-user', '--delete', 'eve'])

# Pulling users.
with Beyond() as b, Infinit(beyond = b) as alice:
  alice.run(['infinit-user', '--create', '--name', 'alice'])
  alice.run(['infinit-user', '--create', '--name', 'bob'])
  alice.run(
    ['infinit-user', '--push', '--name', 'bob', '--email', 'bob@infinit.io'])
  # In the future, we may have a chain of trust allowing a user to pull another.
  try:
    alice.run(['infinit-user', '--pull', '--name', 'bob'])
    unreachable()
  except Exception as e:
    pass
  alice.run(['infinit-user', '--pull', '--as', 'bob', '--name', 'bob'])

# Pull and delete.
with Beyond() as beyond, \
    Infinit(beyond = beyond) as bob, \
    Infinit(beyond = beyond) as alice:
  bob.run(
    ['infinit-user', '--signup', '--name', 'bob', '--email', 'bob@infinit.io'])
  alice.run(['infinit-user', '--create', '--name', 'alice'])
  # Local and Beyond.
  bob.run(
    ['infinit-user', '--delete', '--as', 'bob', '--name', 'bob', '--pull'],
    input = 'bob')
  assertEq(len(bob.run_json(['infinit-user', '--list', '-s'])), 0)
  alice.run(['infinit-user', '--fetch', '--as', 'alice', '--name', 'bob'],
            return_code = 1)
  # Local only.
  alice.run(
    ['infinit-user', '--delete', '--as', 'alice', '--name', 'alice', '--pull'],
    input = 'alice')
  assertEq(len(alice.run_json(['infinit-user', '--list', '-s'])), 0)

# Purge.
with Beyond() as beyond, \
    Infinit(beyond = beyond) as bob, \
    Infinit(beyond = beyond) as alice:
  from os import path
  bob.run(['infinit-user', '--signup', 'b', '--email', 'b@infinit.io'])
  alice.run(['infinit-user', '--signup', 'a', '--email', 'b@infinit.io'])
  # Create basic infrastructure.
  bob.run(['infinit-storage', '--create', '--as', 'b', 's', '--filesystem'])
  bob.run(
    ['infinit-network', '--create', '--as', 'b', 'n', '--storage', 's', '-p'])
  assert not path.exists('%s/b/n' % bob.networks_path)
  assert path.exists('%s/b/b/n' % bob.linked_networks_path)
  bob.run(
    ['infinit-volume', '--create', '--as', 'b', 'v', '--network', 'n', '-p'])
  assert path.exists('%s/b/v' % bob.volumes_path)
  bob.run(['infinit-drive', '--create', '--as', 'b', 'd',
           '--network', 'n', '--volume', 'v'])
  assert path.exists('%s/b/d' % bob.drives_path)
  bob.run(['infinit-user', '--fetch', '--as', 'b', 'a'])
  bob.run(
    ['infinit-passport', '--create', '--as', 'b', '-u', 'a', '-n', 'n', '-p'])
  assert path.exists('%s/b/n/a' % bob.passports_path)
  # Create volume and drive with another owner on bob's network.
  alice.run(['infinit-network', '--fetch', '--as', 'a'])
  assertEq(len(alice.run_json(['infinit-network', '--list', '-s', '--as', 'a'])), 1)
  alice.run(['infinit-passport', '--fetch', '--as', 'a'])
  assertEq(len(alice.run_json(['infinit-passport', '--list', '-s', '--as', 'a'])), 1)
  alice.run(['infinit-network', '--link', '--as', 'a', 'b/n'])
  alice.run(
    ['infinit-volume', '--create', '--as', 'a', 'v', '--network', 'b/n', '-p'])
  alice.run(['infinit-drive', '--create', '--as', 'a', 'd2',
             '-N', 'b/n', '-V', 'v', '-p'])
  alice.run(['infinit-network', '--delete', '--as', 'a', 'b/n'])
  alice.run(
    ['infinit-passport', '--delete', '--as', 'a', '-n', 'b/n', '-u', 'a'])
  # Create new network and invite bob.
  alice.run(['infinit-network', '--create', '--as', 'a', 'n', '-p'])
  alice.run(['infinit-user', '--fetch', 'b'])
  alice.run(['infinit-passport', '--create', '--as', 'a',
             '-n', 'n', '-u', 'b', '-p'])
  bob.run(['infinit-passport', '--fetch', '--as', 'b'])
  assertEq(len(bob.run_json(['infinit-passport', '--list', '-s', '--as', 'b'])), 2)
  assert path.exists('%s/a/n/b' % bob.passports_path)
  # Nuke bob.
  bob.run(['infinit-user', '--delete', '--as', 'b', '--name', 'b',
           '--pull', '--purge'],
          input = 'b')
  # Check that elements have been removed.
  assert not path.exists('%s/b/n' % bob.networks_path)
  assert not path.exists('%s/b/b/n' % bob.linked_networks_path)
  assert not path.exists('%s/b/v' % bob.volumes_path)
  assert not path.exists('%s/b/d' % bob.drives_path)
  assert not path.exists('%s/b/n/a' % bob.passports_path)
  assert not path.exists('%s/a/n/b' % bob.passports_path)
