#!/usr/bin/env python3

from utils import *
import json

# Creating and deleting volumes.
with Infinit() as bob:
  bob.run(['infinit-user', '--create',  'bob'])
  bob.run(['infinit-network', '--create', '--name', 'network', '--as', 'bob'])
  bob.run(['infinit-volume', '--create', '--name', 'volume', '--network', 'network', '--as', 'bob'])
  # Simulate the volume being run and creating it's root block cache directory.
  import os
  state_dir = '%s/.local/state/infinit/filesystem' % bob
  os.makedirs('%s/bob/network/bob/volume' % state_dir)
  bob.run(['infinit-volume', '--export', '--name', 'bob/volume', '--as', 'bob'])
  bob.run(['infinit-volume', '--delete', '--name', 'volume', '--as', 'bob'])
  # Ensure volume root block cache directory is removed.
  assertEq(len(os.listdir('%s/bob/network/bob' % state_dir)), 0)

# Push to the hub.
with Beyond() as beyond, Infinit(beyond = beyond) as bob:
  bob.run(['infinit-user', '--signup',  '--name', 'bob', '--email', 'bob@infinit.io'])
  bob.run(['infinit-network', '--create', '--name', 'network', '--as', 'bob', '--push'])
  bob.run(['infinit-volume', '--create', '--name', 'volume', '--network', 'bob/network', '--as', 'bob', '--push'])
  try:
    bob.run(['infinit-volume', '--push', '--name', 'volume'])
    unreachable()
  except Exception as e:
    pass
  bob.run(['infinit-volume', '--export', '--name', 'bob/volume', '--as', 'bob'])

# Pull and delete.
with Beyond() as beyond, Infinit(beyond = beyond) as bob:
  bob.run(['infinit-user', '--signup', 'bob', '--email', 'b@infinit.io'])
  bob.run(['infinit-network', '--create', '--as', 'bob', 'n', '--push'])
  # Local and Beyond.
  bob.run(['infinit-volume', '--create', '--as', 'bob',
           'v', '--network', 'n', '--push'])
  assertEq(len(bob.run_json(['infinit-volume', '--list', '-s'])), 1)
  bob.run(['infinit-volume', '--delete', '--as', 'bob', 'v', '--pull'])
  assertEq(len(bob.run_json(['infinit-volume', '--list', '-s'])), 0)
  bob.run(['infinit-volume', '--fetch', '--as', 'bob', 'v'], return_code = 1)
  # Local only.
  bob.run(['infinit-volume', '--create', '--as', 'bob', 'v2', '--network', 'n'])
  assertEq(len(bob.run_json(['infinit-volume', '--list', '-s'])), 1)
  bob.run(['infinit-volume', '--delete', '--as', 'bob', 'v2', '--pull'])
  assertEq(len(bob.run_json(['infinit-volume', '--list', '-s'])), 0)

# Purge.
with Beyond() as beyond, Infinit(beyond = beyond) as bob:
  bob.run(['infinit-user', '--signup', 'bob', '--email', 'bob@infinit.io'])
  bob.run(['infinit-storage', '--create', '--as', 'bob', 's', '--filesystem'])
  bob.run(['infinit-network', '--create', '--as', 'bob', 'n', '-S', 's', '-p'])
  bob.run(['infinit-volume', '--create', '--as', 'bob', 'v', '-N', 'n', '-p'])
  assertEq(len(bob.run_json(['infinit-volume', '--list', '-s'])), 1)
  bob.run(['infinit-drive', '--create', '--as', 'bob', 'd',
           '-V', 'v', '-N', 'n', '-p'])
  assertEq(
    len(bob.run_json(['infinit-drive', '--list', '--as', 'bob', '-s'])), 1)
  bob.run(['infinit-volume', '--delete', '--as', 'bob',
           '--purge', '--pull', 'v'])
  assertEq(len(bob.run_json(['infinit-volume', '--list', '-s'])), 0)
  assertEq(
    len(bob.run_json(['infinit-drive', '--list', '--as', 'bob', '-s'])), 0)
  bob.run(['infinit-volume', '--fetch', '--as', 'bob', 'v'], return_code = 1)
  bob.run(['infinit-drive', '--fetch', '--as', 'bob', 'd'], return_code = 1)
