#!/usr/bin/env python3

import os
import sys
sys.path.insert(0, '%s/../../elle/drake/src' % os.path.dirname(__file__))

import drake
import drake.cxx

tk = drake.cxx.GccToolkit(compiler='arm-linux-gnueabihf-g++', compiler_c='arm-linux-gnueabihf-gcc')
tkh = drake.cxx.GccToolkit()
cfg = drake.cxx.Config()
cfg.enable_debug_symbols()
cfg.enable_optimization()

with drake.Drake('../..') as d:
  d.run(
    cxx_toolkit = tk,
    cxx_toolkit_host = tkh,
    cxx_config = cfg,
    valgrind = False,
    python = False,
    beyond = False,
  )
