.TH INFINIT 1
.SH NAME
infinit \- mount an Infinit filesystem

.SH SYNOPSIS
.B infinit
[OPTION]...
[\fB\-\-config\fR \fICONFIG_FILE\fR]

.SH DESCRIPTION
.B infinit
mounts a distributed filesystem as specified by the given configuration file.

.SH OPTIONS
.TP
.BR \-h ", " \-\-help\fR
Display usage.

.TP
.BR \-v ", " \-\-version\fR
Display version.

.TP
.BR \-c ", " \-\-config =\fICONFIG_FILE\fR
Filesystem configuration file.

.SH SEE ALSO
The configuration file documenttion:
.BR infinit (5)
