#!/usr/bin/env python3

import infinit.beyond.bottle

import unittest
import urllib.parse

from utils import *

from copy import deepcopy

with Beyond() as beyond:

  class Test(unittest.TestCase):

    def test_normal(self):
      user = User()
      user.put(beyond)
      network = Network('infinit', owner = user)
      throws(lambda: beyond.get('networks/%s' % network['name']),
             404,
             json = False)
      network.put(beyond, owner = user)
      res = beyond.get('networks/%s' % network['name']).json()
      assert res['name'] == network['name']
      assert res['owner'] == network['owner']

    def test_missing_field(self):
      user = User()
      user.put(beyond)
      for key in ['consensus', 'overlay']:
        network = Network('infinit', owner = user)
        del network[key]
        res = throws(lambda: network.put(beyond, owner = user),
                     400)
        assert 'missing_field' in  res['error']
        assert key in res['error']

    def test_invalid_format(self):
      user = User()
      def infinit_name(name):
        network = Network(name, owner = user)
        res = throws(lambda: network.put(beyond, user),
                     422)
        assert 'invalid_format' in r['error']
      pass

    def test_already_pushed(self):
      # Test same already pushed
      user = User()
      user.put(beyond)
      network = Network('infinit', owner = user)
      res = network.put(beyond, owner = user)
      assertEq(res.status_code, 201)
      res = network.put(beyond, owner = user)
      assertEq(res.status_code, 200)
      # Test conflict
      network['owner'] = {
         "rsa": "MIIBCgKCAQEAxzshG5cp+ky04RtzkjAHXHhBs1sPuNqotxL8rl0MH/jy/dMMkR38+0FAr8M/7bnquj9zHmEpKm3qczcd1kDqnKMbY5w8wgjanzhyLry4SRRQkMlRlEuT+Rgb88EAbXBPBpRGJ5dndkgQrCNALTzJOkt/7S8dJ4EiAMeAJOFEwwSb8nKeb1ciOGoACKOcbzQKjrtCZLK7xaHYvEcD7ztQlIWk8r8COPci2wGi92OYJdGXqNVDSBYS4MMzB8odTKZs25WaGvas8RQ0XlFYNZDP1Aj2vyWKGIjp/KMVjrXwhuJgtEzqbXdJFGf+10FcCJbYav63Hr4Z+9K76rGejFv6nQIDAQAB"
      }
      throws(lambda: network.put(beyond, owner = user), 409)

  if __name__ == '__main__':
    unittest.main()
